# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab1_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tab2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab2_id', models.CharField(max_length=30)),
            ],
        ),
    ]
