# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0003_auto_20170915_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=30, verbose_name='职位')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flame.urltype', verbose_name='搜索网站')),
            ],
            options={
                'verbose_name_plural': '职位网站对照表',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=150, verbose_name='密码'),
        ),
    ]
