# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flame', '0004_auto_20180206_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPositionSsearchWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=100, verbose_name='searched positin')),
                ('website', models.CharField(default='', max_length=50, verbose_name='web name')),
                ('search_time', models.DateField(auto_now_add=True, verbose_name='search time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name_plural': '用户搜索过的职位及对应的网站',
            },
        ),
    ]
