# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0008_auto_20180318_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpositionssearchweb',
            name='search_time',
            field=models.DateField(default=datetime.date(2018, 3, 18), verbose_name='search time'),
        ),
    ]
