# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0010_auto_20180318_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpositionssearchweb',
            name='search_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='search time'),
        ),
    ]
