# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flame', '0013_auto_20180318_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpositionssearchweb',
            name='user',
        ),
        migrations.AddField(
            model_name='position_website',
            name='search_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='search time'),
        ),
        migrations.AddField(
            model_name='position_website',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.DeleteModel(
            name='UserPositionSsearchWeb',
        ),
    ]
