# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0014_auto_20180318_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_website',
            name='count',
            field=models.IntegerField(default=0, verbose_name='searched count'),
        ),
    ]
